{% set name = "automat" %}
{% set version = "25.4.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0017591a5477066e90d26b0e696ddc143baafd87b588cfac8100bc6be9634de0

build:
  entry_points:
    - automat-visualize = automat._visualize:tool
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - m2r
  run:
    - python >={{ python_min }}
    - attrs >=19.2.0
    - six

test:
  requires:
    - python-graphviz >0.5.1
    - twisted >=16.1.1
    - pip
    - python {{ python_min }}
  imports:
    - automat
  commands:
    - pip check
    - automat-visualize -h

about:
  home: https://github.com/glyph/Automat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: self-service finite-state machines for the programmer on the go
  description: |
    Automat is a library for concise, idiomatic Python expression of
    finite-state automata (particularly deterministic finite-state
    transducers).
  doc_url: https://github.com/glyph/automat/
  dev_url: https://github.com/glyph/automat/

extra:
  recipe-maintainers:
    - CJ-Wright
    - ocefpaf
