travis:
  secure:
    BINSTAR_TOKEN: kogepmbk5wzL+aCwIrcA14KexunbDyiI6OObGMxi7uZi5c0iyXFyyc2LS4ggbuMSlRFoRtdNRX+6wZodSdaXJQwB78A0WpIkbS0ZkNReFe6/qLJ8avVmyXAVyBr9yxszDvQ/U3ZaeGarWn3K361L6+Qv3szulzHnLnaTCHnDHUlfmq/x8loWhQSERIFLiVq3yoCL92bA43JVSApFdAYvK1XA2hJVJtqKZOtUB9wnncplsYbb0Zrdt+7jLgKBov4S556lE8jLjzijdGMXX++8T0nYtDpyLYbjXSQ0QjSIs3z+2pW/1ykcgSdxsLZdX8immlb2PqQANYHqvvAak7zRK33HziGsOhFbnIKX1nXuRzUyosuBIWQ3VASkoRMELozOmADpdPhl1fywuDcfKA1GCbQI5RHIJy8/NXQJV4GNMr8R5HZwOVpG7c33AOBJHTDjIPrMvyPqZCht/HPba+og5TNl8VBKU9UyEBuHnNBZ0NYy3Mn5WsEk+lGXIXK6MkpEbdFT2nq0JowACx5ZGHIoLsUzdSnMFj4JT+y7aLABBASytWx66jKIeyCC/3y8tSJcap3v5m24MVVaTtW8sn5Yh3Fh5s3gvfL/f5YOvESMfMwmu3FuSjKFtVmSmmMlbedomHn5Ds/oT6V5jDJn37qHSZzS1Ik6jsZEThCb56pS8xY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
